class TopicsController < ApplicationController
  def index
    topics = current_user.topics.order('updated_at desc')
    render :json => [:topics => topics]
  end

  def create
    folder_autogenerated = false

    if params[:folder_id].nil? || params[:folder_id].to_i <= 0 || current_user.folders.find(params[:folder_id]).nil?
      time = Time.new
      folder = current_user.folders.new
      folder.title = "New #{time.strftime('%b %d')}"
      folder.save
      folder_id = folder.id

      folder_autogenerated = true
    else
      folder_id = params[:folder_id]
    end

    topic = current_user.topics.new(topic_params)
    topic.folder_id = folder_id
    
    if topic.save
      unless folder_autogenerated
        render :json => {:topic => topic}
      else
        render :json => {:topic => topic, :auto_folder => folder}
      end
    else
      render :text => 'error', :status => 409
    end
  end

  def update
    topic = Topic.find(params[:id])

    # temporarily turn off since updated_at controls order of topics in UI
    Topic.record_timestamps = false
    
    if topic.update(topic_params)
      render :text => 'success'
    else
      render :text => 'error', :status => 409
    end

    Topic.record_timestamps = true
  end

  def destroy
    topic = Topic.find(params[:id])
    if topic.destroy
      render :json => {:success => true}
    else
      render :json => {:success => false}, :status => :bad_request
    end
  end

  protected

    def topic_params
      params.permit(:title, :folder_id)
    end
end
